language: minimal
dist: xenial
jobs:
  include:
  - stage: deploy
    if: branch IN (master, develop) OR tag IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ingtranet/knaing-broker:$TRAVIS_BRANCH .
    - docker images
    - docker push ingtranet/knaing-broker:$TRAVIS_BRANCH
notifications:
  slack:
    secure: ma7lOKo5rXOg3mFG5ZCrIWJkabwAihYBBG5Xz4Zp4rQaKFzJfwFTjkdv/GJARBrW91nBaMMXnOh+Zns7tqBocS9/ckXIUgRobto3Af7KTptwG/hERBnTU3qb9T9FSUw9XSPLx8mHpW741TA6iyIB6O9c/77wKuBe0ArS1N7yg0J7Yv0pwIcIdcniBxCuE5ZY/dT3MtJaK1HPdhUhAFzgTji5Qx7rER3TOKwkYyqpeKGnFaji1Z0N5wpzaE6JE86DH4yJZytkkIdgSCT5PVX9uvGqlSj66+BK8Et4S4IF2eL5Hp5htBUcOUB4bKj/wT4l9ar3csgpc+ekrqOPKSmPsaJJYsuXEtTnpv6WieTghcHvAZdPGaqOfesfBe04dZ8emcyX6v24ZY9QEhq+WR8RJrLyY4YxYbBp0uKUfzCObJwnKeRG3ZKSaUsgSVblDp30uAfmrP849C8jsEwfLDDmvPtVIYpbi9s5THDLsP1dxzW8m/GWfjDfINQ0QZ7mGmr+lZb7ZuXLOEnzCv4L2NYtlYKtTwGomBWE/6ZuV4SBN3wwZBTQsJoDb3wPUXwLbXiip30I/h/oDl2f4tMsGS4oDqGJglXLyVvjEjEWEeuK1pJMNEVFd5NsQ0ln24fWNhG1lpl84OeeP60YV7xUESpu7a91gw4IhJas1u705nAaZ98=
